# .github/workflows/deploy.yml

name: Deploy to Production Server

# Trigger this workflow on every push to the main branch
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Checkout the repository code
      # This action checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Deploy to Server via SSH
      # This action uses the provided secrets to connect to your server and run a deployment script.
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }} # <-- Using a private key is more secure
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Navigate to the project directory
            cd /var/www/vhosts/elvirainfotech.org/spencer.elvirainfotech.org

            # Pull the latest changes from the main branch
            git pull origin main

            # --- Add other deployment commands below if needed ---
            # For example, if it's a Node.js project:
            # echo "Installing dependencies..."
            npm install --production
            #
            # echo "Building the application..."
            npm run build
            #
            # echo "Restarting the application..."
            # pm2 restart my-app


            echo "✅ Deployment successful!"
