# .github/workflows/deploy.yml

name: Deploy to Production Server

# Trigger this workflow on every push to the main branch
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Checkout the repository code
      # This action checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Deploy to Server via SSH
      # This action uses the provided secrets to connect to your server and run a deployment script.
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }} # <-- Using a private key is more secure
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Source NVM to load the correct Node.js version
            export PATH="/var/www/vhosts/elvirainfotech.org/.nodenv/shims:$PATH"

            echo "Navigating to the project root directory..."
            cd /var/www/vhosts/elvirainfotech.org/spencer.elvirainfotech.org

            echo "pulling the latest code from the main branch..."
            git pull origin main

            echo "installing dependencies..."
            npm install

            echo migrating 

            echo "running build script..."
            npm run build

            echo "starting/restarting the application with PM2..."
            pm2 startOrRestart ecosystem.config.js --env production --update-env

            echo "Saving PM2 process list..."
            pm2 save --force

            echo "✅ Deployment successful!"
